version: '3.7'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    networks:
      - app
    
  backend:
    container_name: admin-api
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_ROOT_ASSWORD: root
    ports:
    - 8001:8000
    volumes:
    - ..:/app
    depends_on:
      - database
    networks:
      - app

  database:
    container_name: admin-db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - .dbdata:/var/lib/mysql
    ports:
    - 3307:3306
    networks:
      - app

networks:
  app:
  
