version: '3.7'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    networks:
      - app
    
  backend:
    container_name: admin-api
    build:
      context: ..
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: admin_db
      DB_DATABASE: admin
      DB_ROOT_PASSWORD: root
    ports:
    - 8000:8000
    volumes:
    - ..:/app
    - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
    networks:
      - app

  database:
    container_name: admin_db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - .dbdata:/var/lib/mysql
    ports:
    - 3307:3306
    networks:
      - app

networks:
  app:
  
